### ISSUE TITLE
The range header for Heroku releases is fixed - would be good to make it configurable

### ISSUE THREAD

**Issue by stevejalim** [yunojuno-archive/heroku-tools#11]
This line of code:

[https://github.com/yunojuno/heroku-tools/blob/master/heroku_tools/heroku.py#L124](https://github.com/yunojuno/heroku-tools/blob/master/heroku_tools/heroku.py#L124)

from 
```
        releases = call_api(
            HEROKU_API_URL_RELEASES,
            application,
            range_header='version;max=10,order=desc'
        )
```

means that heroku-tools only looks back as far as 10 prev releases when getting a diff to compare. 
The downside of that is, if there have been more than 10 releases with config changes only, it can't find a valid diff to compare the local checkout to, and bails with

```heroku_tools.heroku.HerokuError: No deployments found in API response.```

Makign this `10` configurable, either via a CLI switch or an env var, would get around this issue. It's not a massive deal, but it does crop up

**Comment by hugorodgerbrown** [comment]
This is now implemented as an env var - HEROKU_API_MAX_RANGE, defaults to 10. See commit note for reason why it's not a command option :-)
